### ISSUE TITLE
Receiving the dllNotFound error while executing the Solution in linux/mac/docker environment 

### ISSUE THREAD

**Issue by SeptBlast** [MicrosoftDocs/Azure-RMSDocs#1170]
Need to containerize the Solution Build on Microsoft Information Protection SDK 1.6 in linux Container Architecture. Always receiving common error of dllNotFound.

Error Received while executing MIP Initialization: `MIP.Initialize(MipComponent.File);`

``` varlog
Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Microsoft.InformationProtection.Utils.UnsafeKernel32NativeMethods.LoadLibrary(String dllToLoad)
   at Microsoft.InformationProtection.Utils.Loader.LoadDlls(String dllFolder, String dllName, String[] dllDependencies)
   at Microsoft.InformationProtection.MIP.Initialize(MipComponent mipComponent, String path)
   at MIPSolution.Program.Main(String[] args) in /src/Program.cs:line 55
```

Dockerfile to Execute the Application:

``` Dockerfile
FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY ["MIPSolution.csproj", "./"]
RUN dotnet restore "MIPSolution.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "MIPSolution.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MIPSolution.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# RUN dotnet --info
RUN echo "Build number: $buildno"
ENTRYPOINT ["dotnet", "MIPSolution.dll"]
```

All suggestions to make this application working will be very helpful.

Thanks

**Comment by mlottner** [comment]
@msmbaldwin Can you take a look at this? 
@SeptBlast Thanks for taking the time to comment on docs. I've reassigned this to the person responsible for this content.

**Comment by msmbaldwin** [comment]
Hi, @SeptBlast. Microsoft Information Protection SDK 1.6 did not support running .NET core in Linux. However, the most recent version, 1.7, supports .NET core on Ubuntu 18.04 and Windows. We recommend you upgrade, if you have not already. Thank you. #please-close
